//
//  UIKeyboardHIDUsage+String.swift
//  sample-ipados-pointer-keyboard
//
//  Created by Ryo Nonaka on 2020/09/09.
//  Copyright © 2020 Ryo Nonaka. All rights reserved.
//

import UIKit

extension UIKeyboardHIDUsage {

    var readableKey: String {
        switch self {
        case .keyboardErrorRollOver:
            return "keyboardErrorRollOver"
        case .keyboardPOSTFail:
            return "keyboardPOSTFail"
        case .keyboardErrorUndefined:
            return "keyboardErrorUndefined"
        case .keyboardA:
            return "keyboardA"
        case .keyboardB:
            return "keyboardB"
        case .keyboardC:
            return "keyboardC"
        case .keyboardD:
            return "keyboardD"
        case .keyboardE:
            return "keyboardE"
        case .keyboardF:
            return "keyboardF"
        case .keyboardG:
            return "keyboardG"
        case .keyboardH:
            return "keyboardH"
        case .keyboardI:
            return "keyboardI"
        case .keyboardJ:
            return "keyboardJ"
        case .keyboardK:
            return "keyboardK"
        case .keyboardL:
            return "keyboardL"
        case .keyboardM:
            return "keyboardM"
        case .keyboardN:
            return "keyboardN"
        case .keyboardO:
            return "keyboardO"
        case .keyboardP:
            return "keyboardP"
        case .keyboardQ:
            return "keyboardQ"
        case .keyboardR:
            return "keyboardR"
        case .keyboardS:
            return "keyboardS"
        case .keyboardT:
            return "keyboardT"
        case .keyboardU:
            return "keyboardU"
        case .keyboardV:
            return "keyboardV"
        case .keyboardW:
            return "keyboardW"
        case .keyboardX:
            return "keyboardX"
        case .keyboardY:
            return "keyboardY"
        case .keyboardZ:
            return "keyboardZ"
        case .keyboard1:
            return "keyboard1"
        case .keyboard2:
            return "keyboard2"
        case .keyboard3:
            return "keyboard3"
        case .keyboard4:
            return "keyboard4"
        case .keyboard5:
            return "keyboard5"
        case .keyboard6:
            return "keyboard6"
        case .keyboard7:
            return "keyboard7"
        case .keyboard8:
            return "keyboard8"
        case .keyboard9:
            return "keyboard9"
        case .keyboard0:
            return "keyboard0"
        case .keyboardReturnOrEnter:
            return "keyboardReturnOrEnter"
        case .keyboardEscape:
            return "keyboardEscape"
        case .keyboardDeleteOrBackspace:
            return "keyboardDeleteOrBackspace"
        case .keyboardTab:
            return "keyboardTab"
        case .keyboardSpacebar:
            return "keyboardSpacebar"
        case .keyboardHyphen:
            return "keyboardHyphen"
        case .keyboardEqualSign:
            return "keyboardEqualSign"
        case .keyboardOpenBracket:
            return "keyboardOpenBracket"
        case .keyboardCloseBracket:
            return "keyboardCloseBracket"
        case .keyboardBackslash:
            return "keyboardBackslash"
        case .keyboardNonUSPound:
            return "keyboardNonUSPound"
        case .keyboardSemicolon:
            return "keyboardSemicolon"
        case .keyboardQuote:
            return "keyboardQuote"
        case .keyboardGraveAccentAndTilde:
            return "keyboardGraveAccentAndTilde"
        case .keyboardComma:
            return "keyboardComma"
        case .keyboardPeriod:
            return "keyboardPeriod"
        case .keyboardSlash:
            return "keyboardSlash"
        case .keyboardCapsLock:
            return "keyboardCapsLock"
        case .keyboardF1:
            return "keyboardF1"
        case .keyboardF2:
            return "keyboardF2"
        case .keyboardF3:
            return "keyboardF3"
        case .keyboardF4:
            return "keyboardF4"
        case .keyboardF5:
            return "keyboardF5"
        case .keyboardF6:
            return "keyboardF6"
        case .keyboardF7:
            return "keyboardF7"
        case .keyboardF8:
            return "keyboardF8"
        case .keyboardF9:
            return "keyboardF9"
        case .keyboardF10:
            return "keyboardF10"
        case .keyboardF11:
            return "keyboardF11"
        case .keyboardF12:
            return "keyboardF12"
        case .keyboardPrintScreen:
            return "keyboardPrintScreen"
        case .keyboardScrollLock:
            return "keyboardScrollLock"
        case .keyboardPause:
            return "keyboardPause"
        case .keyboardInsert:
            return "keyboardInsert"
        case .keyboardHome:
            return "keyboardHome"
        case .keyboardPageUp:
            return "keyboardPageUp"
        case .keyboardDeleteForward:
            return "keyboardDeleteForward"
        case .keyboardEnd:
            return "keyboardEnd"
        case .keyboardPageDown:
            return "keyboardPageDown"
        case .keyboardRightArrow:
            return "keyboardRightArrow"
        case .keyboardLeftArrow:
            return "keyboardLeftArrow"
        case .keyboardDownArrow:
            return "keyboardDownArrow"
        case .keyboardUpArrow:
            return "keyboardUpArrow"
        case .keypadNumLock:
            return "keypadNumLock"
        case .keypadSlash:
            return "keypadSlash"
        case .keypadAsterisk:
            return "keypadAsterisk"
        case .keypadHyphen:
            return "keypadHyphen"
        case .keypadPlus:
            return "keypadPlus"
        case .keypadEnter:
            return "keypadEnter"
        case .keypad1:
            return "keypad1"
        case .keypad2:
            return "keypad2"
        case .keypad3:
            return "keypad3"
        case .keypad4:
            return "keypad4"
        case .keypad5:
            return "keypad5"
        case .keypad6:
            return "keypad6"
        case .keypad7:
            return "keypad7"
        case .keypad8:
            return "keypad8"
        case .keypad9:
            return "keypad9"
        case .keypad0:
            return "keypad0"
        case .keypadPeriod:
            return "keypadPeriod"
        case .keyboardNonUSBackslash:
            return "keyboardNonUSBackslash"
        case .keyboardApplication:
            return "keyboardApplication"
        case .keyboardPower:
            return "keyboardPower"
        case .keypadEqualSign:
            return "keypadEqualSign"
        case .keyboardF13:
            return "keyboardF13"
        case .keyboardF14:
            return "keyboardF14"
        case .keyboardF15:
            return "keyboardF15"
        case .keyboardF16:
            return "keyboardF16"
        case .keyboardF17:
            return "keyboardF17"
        case .keyboardF18:
            return "keyboardF18"
        case .keyboardF19:
            return "keyboardF19"
        case .keyboardF20:
            return "keyboardF20"
        case .keyboardF21:
            return "keyboardF21"
        case .keyboardF22:
            return "keyboardF22"
        case .keyboardF23:
            return "keyboardF23"
        case .keyboardF24:
            return "keyboardF24"
        case .keyboardExecute:
            return "keyboardExecute"
        case .keyboardHelp:
            return "keyboardHelp"
        case .keyboardMenu:
            return "keyboardMenu"
        case .keyboardSelect:
            return "keyboardSelect"
        case .keyboardStop:
            return "keyboardStop"
        case .keyboardAgain:
            return "keyboardAgain"
        case .keyboardUndo:
            return "keyboardUndo"
        case .keyboardCut:
            return "keyboardCut"
        case .keyboardCopy:
            return "keyboardCopy"
        case .keyboardPaste:
            return "keyboardPaste"
        case .keyboardFind:
            return "keyboardFind"
        case .keyboardMute:
            return "keyboardMute"
        case .keyboardVolumeUp:
            return "keyboardVolumeUp"
        case .keyboardVolumeDown:
            return "keyboardVolumeDown"
        case .keyboardLockingCapsLock:
            return "keyboardLockingCapsLock"
        case .keyboardLockingNumLock:
            return "keyboardLockingNumLock"
        case .keyboardLockingScrollLock:
            return "keyboardLockingScrollLock"
        case .keypadComma:
            return "keypadComma"
        case .keypadEqualSignAS400:
            return "keypadEqualSignAS400"
        case .keyboardInternational1:
            return "keyboardInternational1"
        case .keyboardInternational2:
            return "keyboardInternational2"
        case .keyboardInternational3:
            return "keyboardInternational3"
        case .keyboardInternational4:
            return "keyboardInternational4"
        case .keyboardInternational5:
            return "keyboardInternational5"
        case .keyboardInternational6:
            return "keyboardInternational6"
        case .keyboardInternational7:
            return "keyboardInternational7"
        case .keyboardInternational8:
            return "keyboardInternational8"
        case .keyboardInternational9:
            return "keyboardInternational9"
        case .keyboardLANG1:
            return "keyboardLANG1"
        case .keyboardLANG2:
            return "keyboardLANG2"
        case .keyboardLANG3:
            return "keyboardLANG3"
        case .keyboardLANG4:
            return "keyboardLANG4"
        case .keyboardLANG5:
            return "keyboardLANG5"
        case .keyboardLANG6:
            return "keyboardLANG6"
        case .keyboardLANG7:
            return "keyboardLANG7"
        case .keyboardLANG8:
            return "keyboardLANG8"
        case .keyboardLANG9:
            return "keyboardLANG9"
        case .keyboardAlternateErase:
            return "keyboardAlternateErase"
        case .keyboardSysReqOrAttention:
            return "keyboardSysReqOrAttention"
        case .keyboardCancel:
            return "keyboardCancel"
        case .keyboardClear:
            return "keyboardClear"
        case .keyboardPrior:
            return "keyboardPrior"
        case .keyboardReturn:
            return "keyboardReturn"
        case .keyboardSeparator:
            return "keyboardSeparator"
        case .keyboardOut:
            return "keyboardOut"
        case .keyboardOper:
            return "keyboardOper"
        case .keyboardClearOrAgain:
            return "keyboardClearOrAgain"
        case .keyboardCrSelOrProps:
            return "keyboardCrSelOrProps"
        case .keyboardExSel:
            return "keyboardExSel"
        case .keyboardLeftControl:
            return "keyboardLeftControl"
        case .keyboardLeftShift:
            return "keyboardLeftShift"
        case .keyboardLeftAlt:
            return "keyboardLeftAlt"
        case .keyboardLeftGUI:
            return "keyboardLeftGUI"
        case .keyboardRightControl:
            return "keyboardRightControl"
        case .keyboardRightShift:
            return "keyboardRightShift"
        case .keyboardRightAlt:
            return "keyboardRightAlt"
        case .keyboardRightGUI:
            return "keyboardRightGUI"
        case .keyboard_Reserved:
            return "keyboard_Reserved"
        @unknown default:
            return "@unknown"
        }
    }

}
